#!/bin/bash

date=$(date +%H)
if [ $date -ge 20 ] || [ $date -le 7 ]; # Night mode
then
{
	/usr/bin/gsettings set org.gnome.desktop.background picture-uri file:///home/$USER/Pictures/wallpapers/dark/$(ls /home/$USER/Pictures/wallpapers/dark/ | sort -R | tail -1)
}
elif [ $date -ge 8 ] && [ $date -le 19 ]; # Day mode
then
{
	/usr/bin/gsettings set org.gnome.desktop.background picture-uri file:///home/$USER/Pictures/wallpapers/light/$(ls /home/$USER/Pictures/wallpapers/light/ | sort -R | tail -1)
}
fi
