#!/bin/bash

# FOR CRONJOB
# export DBUS_SESSION_BUS_ADDRESS environment variable
#PID=$(pgrep gnome-session)
#export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)

echo "Switching to night mode..."
/usr/bin/gsettings set org.gnome.desktop.background picture-uri file:///home/$USER/Pictures/dark/$(ls /home/$USER/Pictures/dark/ | sort -R | tail -1)
